name: Format

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Assets/Scripts/**/*.cs'
      - 'Assets/Tests/**/*.cs'
      - '.editorconfig'
      - 'Directory.Build.props'
      - 'FormatCheck.csproj'
      - '.github/workflows/format-check.yml'
      - '.gitmodules'
      - 'unity-coding-standards'
      - 'unity-coding-standards/**'
  pull_request:
    paths:
      - 'Assets/Scripts/**/*.cs'
      - 'Assets/Tests/**/*.cs'
      - '.editorconfig'
      - 'Directory.Build.props'
      - 'FormatCheck.csproj'
      - '.github/workflows/format-check.yml'
      - '.gitmodules'
      - 'unity-coding-standards'
      - 'unity-coding-standards/**'

jobs:
  format-check:
    name: Check
    uses: void2610/unity-coding-standards/.github/workflows/format-check.yml@main
