name: Steam Deploy 🎮

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  steam-deploy:
    name: Steam Deploy
    uses: void2610/unity-coding-standards/.github/workflows/steam-deploy-self-hosted.yml@main
    with:
      unity-version: 6000.3.10f1
      runner-labels: '["self-hosted","macOS"]'
      nuget-restore-method: Void2610.UnityTemplate.Editor.CI.NuGetRestore.Restore
      windows-execute-method: CiBuild.BuildWindows
      mac-execute-method: CiBuild.BuildMac
      release-branch: test
    secrets:
      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
